### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'frombuffer'

### ISSUE THREAD

**Issue by hmhm1190** [Kaimary/GAR#10]
While runnning the test script I am encountering the following error:

```
(GAR) [husainmalwat@localhost GAR]$ bash test_pipeline.sh "spider" "datasets/spider/dev.json" "datasets/spider/dev_gold.sql" "datasets/spider/tables.json" "datasets/spider/database"
Dataset name: spider
Test JSON file: datasets/spider/dev.json
Gold SQL TXT file: datasets/spider/dev_gold.sql
Schema file of the dataset: datasets/spider/tables.json
Databases directory of the dataset: datasets/spider/database
==================================================================
ACTION REPORT: Testing pipeline starts ......
Re-ranker test data exists!
==================================================================
ACTION REPORT: Start to test re-ranker model /home/husainmalwat/GAR/saved_models/gar.spider/reranker/bertpooler+roberta-base/model.tar.gz
/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
2023-06-19 20:09:10,725 - INFO - allennlp.models.archival - loading archive file /home/husainmalwat/GAR/saved_models/gar.spider/reranker/bertpooler+roberta-base/model.tar.gz
2023-06-19 20:09:10,725 - INFO - allennlp.models.archival - extracting archive file /home/husainmalwat/GAR/saved_models/gar.spider/reranker/bertpooler+roberta-base/model.tar.gz to temp dir /tmp/tmpwtncs7m0
2023-06-19 20:09:14,081 - WARNING - allennlp.common.params - error loading _jsonnet (this is expected on Windows), treating /tmp/tmpwtncs7m0/config.json as plain json
2023-06-19 20:09:14,082 - INFO - allennlp.common.params - dataset_reader.type = listwise_pair_ranker_reader
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.lazy = False
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.cache_directory = None
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.max_instances = 100000
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.manual_distributed_sharding = False
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.manual_multi_process_sharding = False
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.tokenizer.type = pretrained_transformer
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.tokenizer.model_name = roberta-base
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.tokenizer.add_special_tokens = False
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.tokenizer.max_length = None
2023-06-19 20:09:14,083 - INFO - allennlp.common.params - dataset_reader.tokenizer.stride = 0
2023-06-19 20:09:14,084 - INFO - allennlp.common.params - dataset_reader.tokenizer.tokenizer_kwargs = None
2023-06-19 20:09:20,318 - INFO - allennlp.common.params - dataset_reader.token_indexers.bert.type = pretrained_transformer
2023-06-19 20:09:20,318 - INFO - allennlp.common.params - dataset_reader.token_indexers.bert.token_min_padding_length = 0
2023-06-19 20:09:20,318 - INFO - allennlp.common.params - dataset_reader.token_indexers.bert.model_name = roberta-base
2023-06-19 20:09:20,318 - INFO - allennlp.common.params - dataset_reader.token_indexers.bert.namespace = tags
2023-06-19 20:09:20,319 - INFO - allennlp.common.params - dataset_reader.token_indexers.bert.max_length = None
2023-06-19 20:09:20,319 - INFO - allennlp.common.params - dataset_reader.token_indexers.bert.tokenizer_kwargs = None
2023-06-19 20:09:20,320 - INFO - allennlp.common.params - dataset_reader.max_tokens = None
2023-06-19 20:09:20,321 - INFO - allennlp.common.params - validation_dataset_reader.type = listwise_pair_ranker_reader
2023-06-19 20:09:20,321 - INFO - allennlp.common.params - validation_dataset_reader.lazy = False
2023-06-19 20:09:20,321 - INFO - allennlp.common.params - validation_dataset_reader.cache_directory = None
2023-06-19 20:09:20,322 - INFO - allennlp.common.params - validation_dataset_reader.max_instances = None
2023-06-19 20:09:20,322 - INFO - allennlp.common.params - validation_dataset_reader.manual_distributed_sharding = False
2023-06-19 20:09:20,322 - INFO - allennlp.common.params - validation_dataset_reader.manual_multi_process_sharding = False
2023-06-19 20:09:20,322 - INFO - allennlp.common.params - validation_dataset_reader.tokenizer.type = pretrained_transformer
2023-06-19 20:09:20,322 - INFO - allennlp.common.params - validation_dataset_reader.tokenizer.model_name = roberta-base
2023-06-19 20:09:20,323 - INFO - allennlp.common.params - validation_dataset_reader.tokenizer.add_special_tokens = False
2023-06-19 20:09:20,323 - INFO - allennlp.common.params - validation_dataset_reader.tokenizer.max_length = None
2023-06-19 20:09:20,323 - INFO - allennlp.common.params - validation_dataset_reader.tokenizer.stride = 0
2023-06-19 20:09:20,323 - INFO - allennlp.common.params - validation_dataset_reader.tokenizer.tokenizer_kwargs = None
2023-06-19 20:09:20,324 - INFO - allennlp.common.params - validation_dataset_reader.token_indexers.bert.type = pretrained_transformer
2023-06-19 20:09:20,324 - INFO - allennlp.common.params - validation_dataset_reader.token_indexers.bert.token_min_padding_length = 0
2023-06-19 20:09:20,325 - INFO - allennlp.common.params - validation_dataset_reader.token_indexers.bert.model_name = roberta-base
2023-06-19 20:09:20,325 - INFO - allennlp.common.params - validation_dataset_reader.token_indexers.bert.namespace = tags
2023-06-19 20:09:20,325 - INFO - allennlp.common.params - validation_dataset_reader.token_indexers.bert.max_length = None
2023-06-19 20:09:20,325 - INFO - allennlp.common.params - validation_dataset_reader.token_indexers.bert.tokenizer_kwargs = None
2023-06-19 20:09:20,326 - INFO - allennlp.common.params - validation_dataset_reader.max_tokens = None
2023-06-19 20:09:20,326 - INFO - allennlp.common.params - type = from_instances
2023-06-19 20:09:20,326 - INFO - allennlp.data.vocabulary - Loading token dictionary from /tmp/tmpwtncs7m0/vocabulary.
2023-06-19 20:09:20,328 - INFO - allennlp.common.params - model.type = listwise_pair_ranker
2023-06-19 20:09:20,329 - INFO - allennlp.common.params - model.regularizer = None
2023-06-19 20:09:20,329 - INFO - allennlp.common.params - model.text_field_embedder.type = basic
2023-06-19 20:09:20,330 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.type = pretrained_transformer
2023-06-19 20:09:20,330 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.model_name = roberta-base
2023-06-19 20:09:20,330 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.max_length = None
2023-06-19 20:09:20,330 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.sub_module = None
2023-06-19 20:09:20,330 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.train_parameters = True
2023-06-19 20:09:20,331 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.last_layer_only = True
2023-06-19 20:09:20,331 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.override_weights_file = None
2023-06-19 20:09:20,331 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.override_weights_strip_prefix = None
2023-06-19 20:09:20,331 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.gradient_checkpointing = None
2023-06-19 20:09:20,331 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.tokenizer_kwargs = None
2023-06-19 20:09:20,331 - INFO - allennlp.common.params - model.text_field_embedder.token_embedders.bert.transformer_kwargs = None
2023-06-19 20:09:21,282 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpwtncs7m0
Traceback (most recent call last):
  File "/home/husainmalwat/anaconda3/envs/GAR/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 118, in main
    args.func(args)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/commands/predict.py", line 205, in _predict
    predictor = _get_predictor(args)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/commands/predict.py", line 106, in _get_predictor
    archive = load_archive(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/models/archival.py", line 208, in load_archive
    model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/models/archival.py", line 242, in _load_model
    return Model.load(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/models/model.py", line 406, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/models/model.py", line 304, in _load
    model = Model.from_params(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 595, in from_params
    return retyped_subclass.from_params(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 627, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 198, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 305, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 339, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 595, in from_params
    return retyped_subclass.from_params(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 627, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 198, in create_kwargs
    constructed_arg = pop_and_construct_arg(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 305, in pop_and_construct_arg
    return construct_arg(class_name, name, popped_params, annotation, default, **extras)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 380, in construct_arg
    value_dict[key] = construct_arg(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 339, in construct_arg
    return annotation.from_params(params=popped_params, **subextras)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 595, in from_params
    return retyped_subclass.from_params(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/from_params.py", line 629, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/modules/token_embedders/pretrained_transformer_embedder.py", line 74, in __init__
    self.transformer_model = cached_transformers.get(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/allennlp/common/cached_transformers.py", line 84, in get
    transformer = AutoModel.from_pretrained(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2429, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/transformers/modeling_utils.py", line 413, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/home/husainmalwat/anaconda3/envs/GAR/lib/python3.8/site-packages/safetensors/torch.py", line 261, in load_file
    result[k] = f.get_tensor(k)
AttributeError: module 'torch' has no attribute 'frombuffer'
```

**Comment by hmhm1190** [comment]
@Kaimary Would you pls help me in resolving this...

**Comment by Kaimary** [comment]
@hmhm1190 Hi, can you please provide me with the details about your environment? It looks like the version conflicts between your environment and the model checkpoint. 
Please make sure the versions of torch and allennlp packages are the same as specified in the requirement file.
