### ISSUE TITLE
Error SQL statements in training steps

### ISSUE THREAD

**Issue by fengh16** [Kaimary/GAR#3]
Thank you for your excellent work. However, when I used spider to train the model (I used the script `bash train_pipeline.sh spider datasets/spider/train_spider.json datasets/spider/dev.json datasets/spider/tables.json datasets/spider/database`). When `sql_str` is `select count  (  *  )  from follows group by "value"`, an AssertionError occurs: `Error col: "value"`.

I wonder what I should do to solve this problem. **Should I skip all the SQL strings that cause such an error by using a simple try-except statement?**

The traceback is:

```
  4%|█████▊                                                                                                                                           | 278/7000 [00:00<00:18, 371.50it/s]Traceback (most recent call last):
  File "/f/.conda/envs/SQL_GAR/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/f/.conda/envs/SQL_GAR/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/f/code/SQL/GAR/scripts/retrieval_model_train_script.py", line 271, in <module>
    main()
  File "/f/.conda/envs/SQL_GAR/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/f/.conda/envs/SQL_GAR/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/f/.conda/envs/SQL_GAR/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/f/.conda/envs/SQL_GAR/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/f/code/SQL/GAR/scripts/retrieval_model_train_script.py", line 39, in main
    dataset_name, train_file, tables_file, db_dir, output_dir
  File "/f/code/SQL/GAR/scripts/retrieval_model_train_script.py", line 118, in generate_triples_for_retrieval_model
    checker = RecallChecker(data_file, tables_file, db_dir, output_dir)
  File "/f/code/SQL/GAR/utils/recall_checker_utils.py", line 31, in __init__
    self.initialize(dataset_file, tables_file)
  File "/f/code/SQL/GAR/utils/recall_checker_utils.py", line 42, in initialize
    g_sql = rebuild_sql(db_id, self.db_dir, sql_nested_query_tmp_name_convert(query), self.kmaps, tables_file)
  File "/f/code/SQL/GAR/utils/evaluation/evaluate.py", line 537, in rebuild_sql
    sql = get_sql(schema, sql_str)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 630, in get_sql
    _, sql = parse_sql(toks, 0, tables_with_alias, schema)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 566, in parse_sql
    idx, group_col_units = parse_group_by(toks, idx, tables_with_alias, schema, default_tables)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 477, in parse_group_by
    idx, col_unit = parse_col_unit(toks, idx, tables_with_alias, schema, default_tables)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 241, in parse_col_unit
    idx, col_id = parse_col(toks, idx, tables_with_alias, schema, default_tables)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 209, in parse_col
    assert False, "Error col: {}".format(tok)
AssertionError: Error col: "value"
RESULT REPORT: Retrieval model fine-tune data failed!
```

(Because I added `print(sql_str)` to the Line 536 of `utils/evaluation/evaluate.py`, `File "/f/code/SQL/GAR/utils/evaluation/evaluate.py", line 537, in rebuild_sql` should be Line 536)

**Comment by Kaimary** [comment]
@fengh16 Hi Henry! It looks like a normalization bug in the Spider data, which wrongly recognizes the f1 column as a literal, and hence uses the "value" as the placeholder. You can just skip this particular instance, or edit line 36316 of the train_spider.json file to "f1".

Side note: I cannot remember if there have other problematic instances (like this) in the original train set. Just uploaded a copy of the data on my end for your reference,
https://drive.google.com/file/d/1dxSK2jlrQyzr38jYrXZsIa76CF_d2hGY/view?usp=share_link

**Comment by fengh16** [comment]
Thanks! It works with your file.
