### ISSUE TITLE
Issue in the code to run the Train script and evaluation script

### ISSUE THREAD

**Issue by hmhm1190** [Kaimary/GAR#5]
**I am not getting what arguments to be given while running the training script and evaluation script**
Would yo pls mention the local path that you are using for each of these arguments...

$ bash train_pipeline.sh <dataset_name> <train_data_path> <dev_data_path> <table_path> <db_dir>

$ bash test_pipeline.sh <dataset_name>  <test_file_path> <test_gold_sql_file> <table_path> <db_dir>

**Comment by Kaimary** [comment]
@hmhm1190 Following is an example command I used for the Spider dataset, FYI.

bash train_pipeline.sh "spider" "datasets/spider/train_spider.json" "datasets/spider/dev.json" "datasets/spider/tables.json" "datasets/spider/database"
bash test_pipeline.sh "spider" "datasets/spider/dev.json" "datasets/spider/dev_gold.sql" "datasets/spider/tables.json" "datasets/spider/database"

**Comment by hmhm1190** [comment]
Hi @Kaimary ,
Thanks so much for your response! Would help me with the necessary changes to test the model on my own database and NL Questions.

**Comment by Kaimary** [comment]
@hmhm1190 To test the model on your own database, you just need to prepare the sample query file and schema file(Spider data format) and run the test_pipeline.sh as above. If you have a separate sample query file and test NL query file, please use the generalization_script.py script to do the generalization first, and then run the test_pipeline.sh script.

**Comment by suriyavarman2** [comment]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\tessadmin\Music\GAR-main\scripts\retrieval_model_train_script.py", line 271, in <module>
    main()
  File "C:\Users\tessadmin\anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\scripts\retrieval_model_train_script.py", line 38, in main
    output_train_data = generate_triples_for_retrieval_model(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\scripts\retrieval_model_train_script.py", line 118, in generate_triples_for_retrieval_model
    checker = RecallChecker(data_file, tables_file, db_dir, output_dir)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\recall_checker_utils.py", line 31, in __init__
    self.initialize(dataset_file, tables_file)
  File "C:\Users\tessadmin\Music\GAR-main\utils\recall_checker_utils.py", line 42, in initialize
    g_sql = rebuild_sql(db_id, self.db_dir, sql_nested_query_tmp_name_convert(query), self.kmaps, tables_file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\evaluation\evaluate.py", line 536, in rebuild_sql
    sql = get_sql(schema, sql_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\evaluation\process_sql.py", line 638, in get_sql
    _, sql = parse_sql(toks, 0, tables_with_alias, schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\evaluation\process_sql.py", line 574, in parse_sql
    idx, group_col_units = parse_group_by(toks, idx, tables_with_alias, schema, default_tables)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\evaluation\process_sql.py", line 485, in parse_group_by
    idx, col_unit = parse_col_unit(toks, idx, tables_with_alias, schema, default_tables)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\evaluation\process_sql.py", line 249, in parse_col_unit
    idx, col_id = parse_col(toks, idx, tables_with_alias, schema, default_tables)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tessadmin\Music\GAR-main\utils\evaluation\process_sql.py", line 215, in parse_col
    assert False, "Error col: {}".format(tok)
AssertionError: Error col: value
RESULT REPORT: Retrieval model fine-tune data failed!
Error while running this command:
bash train_pipeline.sh "spider" "datasets/spider/train_spider.json" "datasets/spider/dev.json" "datasets/spider/tables.json" "datasets/spider/database"
