### ISSUE TITLE
Error SQL statements in the test steps

### ISSUE THREAD

**Issue by fengh16** [Kaimary/GAR#9]
It seems that the `value filter stage` failed because there is a wrong table name `events` in the SQL statement.

For the SQL `SELECT EVENTS.EVENT_DETAILS , PARTICIPANTS_IN_EVENTS.EVENT_ID FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID GROUP BY PARTICIPANTS_IN_EVENTS.EVENT_ID HAVING COUNT  (  *  )  > 'VALUE'`, there is an error:

```
Traceback (most recent call last):                                                                                                                  File "/f/.conda/envs/SQL_GAR2/lib/python3.7/runpy.py", line 193, in _run_module_as_main                                                             "__main__", mod_spec)                                                                                                                           File "/f/.conda/envs/SQL_GAR2/lib/python3.7/runpy.py", line 85, in _run_code                                                                    
    exec(code, run_globals)                                                                                                                       
  File "/f/code/SQL/GAR/scripts/value_postprocessing/candidate_filter_top10.py", line 187, in <module>                                            
    main()                                                                                                                                        
  File "/f/.conda/envs/SQL_GAR2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/f/.conda/envs/SQL_GAR2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/f/.conda/envs/SQL_GAR2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/f/.conda/envs/SQL_GAR2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/f/code/SQL/GAR/scripts/value_postprocessing/candidate_filter_top10.py", line 158, in main
    tmp = candidate_filter(candidates, db_id, db_context, tables_file, database_dir)
  File "/f/code/SQL/GAR/scripts/value_postprocessing/candidate_filter_top10.py", line 97, in candidate_filter
    sql_dict = rebuild_sql(db_id, dataset_path, sql_nested_query_tmp_name_convert(candidate), kmaps)
  File "/f/code/SQL/GAR/utils/evaluation/evaluate.py", line 536, in rebuild_sql
    sql = get_sql(schema, sql_str)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 630, in get_sql
    _, sql = parse_sql(toks, 0, tables_with_alias, schema)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 556, in parse_sql
    from_end_idx, table_units, conds, default_tables = parse_from(toks, start_idx, tables_with_alias, schema)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 433, in parse_from
    idx, table_unit, table_name = parse_table_unit(toks, idx, tables_with_alias, schema)
  File "/f/code/SQL/GAR/utils/evaluation/process_sql.py", line 281, in parse_table_unit
    key = tables_with_alias[toks[idx]]
KeyError: 'events'
RESULT REPORT: Value filter result failed!
```

Thank you in advance! Maybe there is something that I need to modify in the datasets.

**Comment by Kaimary** [comment]
@fengh16 May you, please, provide me the input file for the value filtering step? So that I can test from my side to see if this is a bug for the code.

**Comment by fengh16** [comment]
The input file (`output/data=spider,num1=20000,num2=100,model1=stsb-mpnet-base-v2,model2=bertpooler+roberta-base/pred_sql_topk.txt`) is uploaded to https://drive.google.com/file/d/1JoQanN4r58OQDnUTIsfxwtX2uvOJK8tT/view?usp=sharing .

This file contains

```
SELECT EVENTS.EVENT_DETAILS FROM EVENTS AS T1 JOIN SERVICES AS T2 ON T1.SERVICE_ID = T2.SERVICE_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_ID FROM EVENTS AS T1 JOIN SERVICES AS T2 ON T1.SERVICE_ID = T2.SERVICE_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_DETAILS FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID JOIN SERVICES AS T3 ON T1.SERVICE_ID = T3.SERVICE_ID JOIN PARTICIPANTS AS T4 ON T4.PARTICIPANT_ID = T2.PARTICIPANT_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_DETAILS, SERVICES.SERVICE_TYPE_CODE FROM EVENTS AS T1 JOIN SERVICES AS T2 ON T1.SERVICE_ID = T2.SERVICE_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_DETAILS FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID JOIN SERVICES AS T3 ON T1.SERVICE_ID = T3.SERVICE_ID JOIN PARTICIPANTS AS T4 ON T4.PARTICIPANT_ID = T2.PARTICIPANT_ID WHERE PARTICIPANTS.PARTICIPANT_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_DETAILS , EVENTS.EVENT_ID FROM EVENTS AS T1 JOIN SERVICES AS T2 ON T1.SERVICE_ID = T2.SERVICE_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT PARTICIPANTS_IN_EVENTS.EVENT_ID FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID JOIN SERVICES AS T3 ON T1.SERVICE_ID = T3.SERVICE_ID JOIN PARTICIPANTS AS T4 ON T4.PARTICIPANT_ID = T2.PARTICIPANT_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_DETAILS, SERVICES.SERVICE_TYPE_CODE FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID JOIN SERVICES AS T3 ON T1.SERVICE_ID = T3.SERVICE_ID JOIN PARTICIPANTS AS T4 ON T4.PARTICIPANT_ID = T2.PARTICIPANT_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_DETAILS , PARTICIPANTS.PARTICIPANT_DETAILS FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID JOIN SERVICES AS T3 ON T1.SERVICE_ID = T3.SERVICE_ID JOIN PARTICIPANTS AS T4 ON T4.PARTICIPANT_ID = T2.PARTICIPANT_ID WHERE SERVICES.SERVICE_TYPE_CODE = 'VALUE'
SELECT EVENTS.EVENT_ID FROM EVENTS AS T1 JOIN PARTICIPANTS_IN_EVENTS AS T2 ON T1.EVENT_ID = T2.EVENT_ID JOIN SERVICES AS T3 ON T1.SERVICE_ID = T3.SERVICE_ID JOIN PARTICIPANTS AS T4 ON T4.PARTICIPANT_ID = T2.PARTICIPANT_ID WHERE PARTICIPANTS.PARTICIPANT_TYPE_CODE = 'VALUE'
```

However, if I only keep these SQL statements in this file, the code will not cause the same error.

**Comment by Kaimary** [comment]
@fengh16 It Looks like the alias inconsistency leads to the error. Please check if the function use_alias() resolves the issue.
